[
  {
    "username":"gizakof0",
    "password":"tX0QRen~E\"9"
  },
  {
    "username":"nlancastle1",
    "password":"dI9g`lb|7\\I,1+"
  },
  {
    "username":"jmanns2",
    "password":"bV1oIgfHP2G#,"
  },
  {
    "username":"mshiel3",
    "password":"cD7Jx`ou'"
  },
  {
    "username":"swalstow4",
    "password":"iH6MXqZG3Y2.t"
  },
  {
    "username":"ckedwell5",
    "password":"lA3ug@}hX6"
  },
  {
    "username":"rsuddick6",
    "password":"kH9jtRrvYc`@)"
  },
  {
    "username":"tbeartup7",
    "password":"jU8(Rt2Y!j*"
  },
  {
    "username":"bmann8",
    "password":"wV3xu*d|~/z23Y's"
  },
  {
    "username":"amckearnen9",
    "password":"yE8eAx}tdm9)"
  },
  {
    "username":"vgreenalfa",
    "password":"lG2(!(&1h+HI~bv"
  },
  {
    "username":"tcutmareb",
    "password":"lV2)K12N|toxBC"
  },
  {
    "username":"jcorbertc",
    "password":"xN3Y7s8gN/"
  },
  {
    "username":"roconord",
    "password":"wL0W?\",LZt"
  },
  {
    "username":"lduigane",
    "password":"uN3N)UXj"
  },
  {
    "username":"mpervoef",
    "password":"sA9m7$Vis"
  },
  {
    "username":"hpryellg",
    "password":"kV7r$rddUeTT"
  },
  {
    "username":"hmacgownh",
    "password":"hS40HD!.2z1"
  },
  {
    "username":"aminteri",
    "password":"vA4+4VLpF"
  },
  {
    "username":"zrowterj",
    "password":"uD2pVs*N{1("
  }
]